blank_issues_enabled: true
contact_links:
  - name: Spock Gitter Chat
    url: https://gitter.im/spockframework/spock
    about: Please ask and answer questions here.
  - name: Spock Stackoverflow
    url: https://stackoverflow.com/questions/tagged/spock
    about: For questions of the type "why isn't this working".
  - name: Spock Discussions
    url: https://github.com/spockframework/spock/discussions
    about: For other questions and discussions.
