/*
 * Copyright 2012 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.spockframework.mock.response;

import org.spockframework.mock.*;
import org.spockframework.util.ThreadSafe;

import java.util.function.Supplier;

@ThreadSafe
public abstract class SingleResponseGenerator implements IChainableResponseGenerator {
  private volatile boolean endOfCycle = false;

  @Override
  public boolean isAtEndOfCycle() {
    return endOfCycle;
  }

  @Override
  public final Supplier<Object> getResponseSupplier(IMockInvocation invocation) {
    endOfCycle = true;
    return doGetResponseSupplier(invocation);
  }

  /**
   * Do not call this method from Spock 2.4 on! Some subclasses of this class have the need to overwrite
   * {@link #doGetResponseSupplier(IMockInvocation)} instead and throw an exception if this method is called directly.
   * Always use {@code doGetResponseSupplier} instead to retrieve a response from this single response generator.
   *
   * <p>If you subclass this class and can directly provide the generated response, you can overwrite this
   * method and use the default implementation of {@code doGetResponseSupplier} which uses this method. If you are in
   * need to manage some state, like advancing an iterator or similar, or the actual supplying can deadlock,
   * or you might throw an exception, you might want to overwrite {@code doGetResponseSupplier} instead and keep
   * the default implementation of this method which throws an {@code UnsupportedOperationException}.
   *
   * <p>This method is mainly kept for backwards compatibility with code that subclasses this class.
   * Most usages where this method is called will most likely fail to execute now.
   *
   * @param invocation The invocation to generate a response for
   * @return The generated response
   * @throws UnsupportedOperationException if {@code doGetResponseSupplier} must be used instead
   * @deprecated Use {@link #doGetResponseSupplier(IMockInvocation)} instead
   */
  @Deprecated
  public Object doRespond(IMockInvocation invocation) {
    throw new UnsupportedOperationException("Call doGetResponseSupplier(invocation) instead");
  }

  /**
   * This method should be used from Spock 2.4 on, to get a response generated by this single response generator.
   * Calling {@link #doRespond(IMockInvocation)} directly might throw an {@code UnsupportedOperationException}, if
   * this single response generator needs to do some state maintenance or other things in this method's implementation.
   *
   * <p>If you subclass this class and can directly provide the generated response, you can overwrite
   * {@code doRespond} and use the default implementation of this method which uses that method. If you are in
   * need to manage some state, like advancing an iterator or similar, or the actual supplying can deadlock,
   * or you might throw an exception, you might want to override this method instead and keep the default
   * implementation of {@code doRespond} which throws an {@code UnsupportedOperationException}.
   *
   * @param invocation The invocation to generate a response for
   * @return A supplier that provides the generated response
   */
  public Supplier<Object> doGetResponseSupplier(IMockInvocation invocation) {
    return () -> doRespond(invocation);
  }
}
