name: Setup JDKs
description: Sets up JDKs
inputs:
  additional-java-version:
    required: true
    description: Additional Java version to install
runs:
  using: "composite"
  steps:
    - name: 'Set up JDK ${{ inputs.additional-java-version }}'
      uses: actions/setup-java@v2
      if: inputs.additional-java-version != 8
      with:
        distribution: 'adopt'
        java-version: ${{ inputs.additional-java-version }}
    - name: 'Prepare JDK${{ inputs.additional-java-version }} env var'
      shell: bash
      run: echo "JDK${{ inputs.additional-java-version }}=$JAVA_HOME" >> $GITHUB_ENV
    - name: 'Set up JDK 8'
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 8
    - name: Prepare JDK8 env var
      shell: bash
      run: echo "JDK8=$JAVA_HOME" >> $GITHUB_ENV
