name: Setup JDKs
description: Sets up JDKs
inputs:
  additional-java-version:
    required: true
    description: Additional Java version to install
runs:
  using: "composite"
  steps:
    - name: 'Set up JDK ${{ inputs.additional-java-version }}'
      uses: actions/setup-java@v3
      if: inputs.additional-java-version != 8 && inputs.additional-java-version != 17
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.additional-java-version }}
    - name: 'Prepare JDK${{ inputs.additional-java-version }} env var'
      shell: bash
      run: echo "JDK${{ inputs.additional-java-version }}=$JAVA_HOME" >> $GITHUB_ENV
    # We need JDK to compile Spock Core
    - name: 'Set up JDK 8'
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 8
    - name: Prepare JDK8 env var
      shell: bash
      run: echo "JDK8=$JAVA_HOME" >> $GITHUB_ENV
    # We need JDK 11 for the Gradle build logic
    - name: 'Set up JDK 17'
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Prepare JDK11 env var
      shell: bash
      run: echo "JDK17=$JAVA_HOME" >> $GITHUB_ENV
