[[spring-module]]
= Spring Module
include::include.adoc[]

The Spring module enables integration with https://docs.spring.io/spring/docs/4.1.5.RELEASE/spring-framework-reference/html/testing.html#testcontext-framework[Spring TestContext Framework].
It supports the following spring annotations `@ContextConfiguration` and `@ContextHierarchy`. Furthermore, it supports the meta-annotation `@BootstrapWith` and so any annotation that is annotated with `@BootstrapWith` will also work, such as `@SpringBootTest`, `@WebMvcTest`. Please add dependency https://search.maven.org/artifact/org.spockframework/spock-spring[`org.spockframework:spock-spring`] to your project.

[[SpringMocks]]
== Mocks

Spock 1.1 introduced the `DetachedMockFactory` and the `SpockMockFactoryBean` which allow the creation of Spock mocks outside of a specification.

NOTE: Although the mocks can be created outside of a specification, they only work properly inside the scope of a specification.
      All interactions with them until they are attached to one, are handled by the default behavior and not recorded.
      +
      Furthermore, mocks can only be attached to one `Specification` instance at a time so keep that in mind when using multi-threaded executions

=== Java Config

[source,groovy,indent=0]
----
include::{sourcedir-spring}/DetachedJavaConfig.groovy[tag=javaconfig]
----

=== XML

Spock has spring namespace support, so if you declare the spock namespace with `xmlns:spock="https://www.spockframework.org/spring"` you get access to the convenience functions for creating mocks.

[source,xml,indent=0]
----
include::{resourcedir-spring}/MockDocu-context.xml[]
----
<1> Creates a `Mock`
<2> Creates a `Stub`
<3> Creates a `Spy`
<4> Wraps an existing bean with a `Spy`. Fails fast if referenced bean is not found.
<5> If you don't want to use the special namespace support you can create the beans via the `SpockMockFactoryBean`
<6> The `mockNature` can be `MOCK`, `STUB`, or `SPY` and defaults to `MOCK` if not declared.

=== Usage

To use the mocks just inject them like any other bean and configure them as usual.

[source,groovy,indent=0]
----
include::{sourcedir-spring}/MockExamples.groovy[tag=example]
----

=== Annotation driven

Spock 1.2 adds support for exporting mocks from a `Specification` into an `ApplicationContext`. This was inspired by
Spring Boot's `@MockBean`(realised via Mockito) but adapted to fit into Spock style. It does not require any Spring Boot dependencies,
however it requires Spring Framework 4.3.5 or greater to work.

==== Using `@SpringBean`

Registers mock/stub/spy as a spring bean in the test context.

To use `@SpringBean` you have to use a strongly typed field `def` or `Object` won't work. You also need to directly assign the
`Mock`/`Stub`/`Spy` to the field using the standard Spock syntax. You can even use the initializer blocks to define common behavior,
however they are only picked up once they are attached to the `Specification`.

`@SpringBean` definitions can replace existing Beans in your `ApplicationContext`.

NOTE: Spock's `@SpringBean` actually creates a proxy in the `ApplicationContext` which forwards everything to the current
      mock instance. The type of the proxy is determined by the type of the annotated field.
      +
      The proxy attaches itself to the current mock in the setup phase, that is why the mock must be created when the field is initialized.

[source,groovy,indent=0]
----
include::{sourcedir-spring}/SpringBeanExamples.groovy[tag=example]
----

CAUTION: As with Spring's own `@MockBean` this will modify your `ApplicationContext`, and will create an unique context for your
         `Specification` preventing it from being reused by Spring's
         https://docs.spring.io/spring/docs/current/spring-framework-reference/testing.html#testcontext-ctx-management-caching[Context Caching]
         outside of the current `Specification`.
         +
         If you are using a small context this won't matter much, but if it is a heavy context you might want to use
         the other approaches, e.g., using the `DetachedMockFactory`.

==== Using `@SpringSpy`

If you want to spy on an existing bean, you can use the `@SpringSpy` annotation to wrap the bean in a spy.
As with `@SpringBean` the field must be of the type you want to spy on, however you cannot use an initializer.

[source,groovy,indent=0]
----
include::{sourcedir-spring}/SpringSpyExamples.groovy[tag=example]
----

==== Using `@StubBeans`

`@StubBeans` registers plain `Stub` instances in an `ApplicationContext`.
Use this if you just need to satisfy some dependencies without actually doing anything with these stubs.
If you need to control the stubs, e.g., configure return values then use `@SpringBean` instead.
Like `@SpringBean` `@StubBeans` also replaced existing BeanDefinitions,so you can use it to remove real beans from an ApplicationContext.
`@StubBeans` can be replaced by `@SpringBean`, this can be useful if you need to replace some `@StubBeans` defined in a parent class.

[source,groovy,indent=0]
----
include::{sourcedir-spring}/StubBeansExamples.groovy[tag=example]
----

=== Spring Boot

The recommended way to use Spock mocks in `@WebMvcTest` or other `@SpringBootTest`-style tests,
is to use the `@SpringBean` and `@SpringSpy` annotations as shown above.

Alternatively you can use an embedded config annotated with `@TestConfiguration` and to create the mocks using the `DetachedMockFactory`.

[source,groovy,indent=0]
----
include::{sourcedir-spring-boot}/WebMvcTestIntegrationSpec.groovy[tag=include]
----


For more examples see the specs in the https://github.com/spockframework/spock/tree/master/spock-spring/src/test/groovy/org/spockframework/spring[codebase] and https://github.com/spockframework/spock/tree/master/spock-spring/boot-test/src/test/groovy/org/spockframework/boot[boot examples].

== Scopes

Spock ignores bean that is not a `singleton` (in the `singleton` scope) by default. To enable mocks to work for scoped beans
you need to add `@ScanScopedBeans` to the spec and make sure that the scope allows access to the bean during the setup phase.

NOTE: The `request` and `session` scope will throw exceptions by default, if there is no active request/session.

You can limit the scanning to certain scopes by using the `value` property of `@ScanScopedBeans`.

== Shared fields injection

Due to certain limitations, injection into shared fields is not enabled by default but can be opted-in to.
Refer to javadoc of `org.spockframework.spring.EnableSharedInjection` for further information.
