= Spring Module
include::include.adoc[]

The Spring module enables integration with http://docs.spring.io/spring/docs/4.1.5.RELEASE/spring-framework-reference/html/testing.html#testcontext-framework[Spring TestContext Framework].
It supports the following spring annotations `@ContextConfiguration` and `@ContextHierarchy`. Furthermore, it supports the meta-annotation `@BootstrapWith` and so any annotation that is annotated with `@BootstrapWith` will also work, such as `@SpringBootTest`, `@WebMvcTest`.

== Mocks

Spock 1.1 introduced the `DetachedMockFactory` and the `SpockMockFactoryBean` which allow the creation of Spock mocks outside of a specification.

[NOTE]
====
Although the mocks can be created outside of a specification,
they only work inside the scope of a specification. So don't perform any actions on them until they are attached to one.
====

=== Java Config


[source,groovy,indent=0]
----
include::{sourcedir-spring}/DetachedJavaConfig.groovy[tag=javaconfig]
----

=== XML

Spock has spring namespace support, so if you declare the spock namespace with `xmlns:spock="http://www.spockframework.org/spring"` you get access to the convenience functions for creating mocks.

[source,xml,indent=0]
----
include::{resourcedir-spring}/MockDocu-context.xml[]
----
<1> Creates a `Mock`
<2> Creates a `Stub`
<3> Creates a `Spy`
<4> Wraps an existing bean with a `Spy`. Fails fast if referenced bean is not found.
<5> If you don't want to use the special namespace support you can create the beans via the `SpockMockFactoryBean`
<6> The `mockNature` can be `MOCK`, `STUB`, or `SPY` and defaults to `MOCK` if not declared.

=== Usage

To use the mocks just inject them like any other bean and configure them as usual.

[source,groovy,indent=0]
----
include::{sourcedir-spring}/MockExamples.groovy[tag=example]
----

=== Spring Boot

The recommended way to use Spock mocks in `@WebMvcTest` tests, is to use an embedded config annotated with `@TestConfiguration` and to create the mocks using the `DetachedMockFactory`.

[source,groovy,indent=0]
----
include::{sourcedir-spring-boot}/WebMvcTestIntegrationSpec.groovy[tag=include]
----


For more examples see the specs in the https://github.com/spockframework/spock/tree/master/spock-spring/src/test/groovy/org/spockframework/spring[codebase] and https://github.com/spockframework/spock/tree/master/spock-spring/boot-test/src/test/groovy/org/spockframework/boot[boot examples].

== Scopes

Spock ignores bean that is not a `singleton` (in the `singleton` scope) by default. To enable mocks to work for scoped beans
you need to add `@ScanScopedBeans` to the spec and make sure that the scope allows access to the bean during the setup phase.

NOTE: The `request` and `session` scope will throw exceptions by default, if there is no active request/session.

You can limit the scanning to certain scopes by using the `value` property of `@ScanScopedBeans`.
