= Modules
include::include.adoc[]

[[junit-4]]
== JUnit 4 Module

Integration with JUnit 4 features for Spock 2+ (which internally uses JUnit Platform - part of JUnit 5). Please add dependency https://search.maven.org/artifact/org.spockframework/spock-junit4[`org.spockframework:spock-junit4`] to your project.

The module is required for:

 - running JUnit 4 rules and class ruless (`@Rule`/`@ClassRule`)
 - using JUnit 4's test fixture annotations (`@BeforeClass`, `@Before`, `@After`, `@AfterClass`)

NOTE: This module does its best to support old features from JUnit 4, however, users are encouraged to migrate to the native Spock counterparts.


== Guice Module

Integration with the http://code.google.com/p/google-guice/[Guice] IoC container. Please add dependency https://search.maven.org/artifact/org.spockframework/spock-guice[`org.spockframework:spock-guice`] to your project. For examples see the specs in the
https://github.com/spockframework/spock/tree/master/spock-guice/src/test/groovy/org/spockframework/guice[codebase].

With Spock 1.2+ detached mocks are automatically attached to the `Specification` if they are injected via `@Inject`.

include::module_spring.adoc[leveloffset=+1]


== Tapestry Module

Integration with the http://tapestry.apache.org/tapestry5/[Tapestry5] IoC container. Please add dependency https://search.maven.org/artifact/org.spockframework/spock-tapestry[`org.spockframework:spock-tapestry`] to your project. For examples see the specs in the
https://github.com/spockframework/spock/tree/master/spock-tapestry/src/test/groovy/org/spockframework/tapestry[codebase].


== Unitils Module

Integration with the http://www.unitils.org/[Unitils] library. Please add dependency https://search.maven.org/artifact/org.spockframework/spock-unitils[`org.spockframework:spock-unitils`] to your project. For examples see the specs in the
https://github.com/spockframework/spock/tree/master/spock-unitils/src/test/groovy/org/spockframework/unitils[codebase].


== Grails Module

The Grails plugin has moved to its own https://github.com/spockframework/spock-grails[GitHub project]. It has legacy status and was last released for https://search.maven.org/artifact/org.spockframework/spock-grails[Spock 0.7 and Groovy versions 1.8 and 2.0], because it is no longer necessary.

NOTE: Grails 2.3 and higher have built-in Spock support and do not require a plugin.
