= Modules
include::include.adoc[]

[[junit-4]]
== JUnit 4 Module

Integration with JUnit 4 features for Spock 2+ (which internally uses JUnit Platform - part of JUnit 5).

The module is required for:

 - running JUnit 4 rules and class ruless (`@Rule`/`@ClassRule`)
 - using JUnit 4's test fixture annotations (`@BeforeClass`, `@Before`, `@After`, `@AfterClass`)

NOTE: This module does its best to support old features from JUnit 4, however, users are encouraged to migrate to the native Spock counterparts.


== Guice Module

Integration with the http://code.google.com/p/google-guice/[Guice] IoC container. For examples see the specs in the
https://github.com/spockframework/spock/tree/master/spock-guice/src/test/groovy/org/spockframework/guice[codebase].

With Spock 1.2+ detached mocks are automatically attached to the `Specification` if they are injected via `@Inject`.

include::module_spring.adoc[leveloffset=+1]


== Tapestry Module

Integration with the http://tapestry.apache.org/tapestry5/[Tapestry5] IoC container. For examples see the specs in the
https://github.com/spockframework/spock/tree/master/spock-tapestry/src/test/groovy/org/spockframework/tapestry[codebase].


== Unitils Module

Integration with the http://www.unitils.org/[Unitils] library. For examples see the specs in the
https://github.com/spockframework/spock/tree/master/spock-unitils/src/test/groovy/org/spockframework/unitils[codebase].


== Grails Module

The Grails plugin has moved to its own https://github.com/spockframework/spock-grails[GitHub project].

NOTE: Grails 2.3 and higher have built-in Spock support and do not require a plugin.
