[[release-notes]]
= Release Notes
include::include.adoc[]
:SpecClassFileSelector: https://github.com/spockframework/spock/blob/03818ed010f4b4ca1136a292e214f79d518c4abe/spock-core/src/main/java/org/spockframework/buildsupport/ant/SpecClassFileSelector.java
:scriptselector: {spock-example-project}/blob/963fd34d1609b7025ba92502483ce31b2c6d9d0a/build.xml#L167-L176

== 2.5 (tbd)

== 2.4 (2025-12-11)

_This is a summary of the highlights of the milestone releases_

=== Highlights

* Add support for Groovy 5.0 spockIssue:2196[]
* Add support for combining two or more data providers using Cartesian product spockIssue:1062[]
* Add support for a `filter` block after a `where` block to filter out unwanted iterations spockPull:1927[]
* Add <<extensions.adoc#block-listener,`IBlockListener`>> extension point to listen to block execution events within feature methods spockPull:1575[]
* Add support for defining condition blocks with implicit assertions in helper methods annotated with `@Verify` or `@VerifyAll` spockPull:2112[]
* Add support for pluggable <<extensions.adoc#mock-makers,mock makers>> loaded via ServiceLoader spockPull:1746[]
** This allows external libraries to contribute mocking logic to Spock and use the same API for the users
** You can select the used mock maker during mock creation: `Mock(mockMaker:MockMakers.byteBuddy)`
* Add <<extensions.adoc#mock-makers-mockito,mockito>> mock maker spockPull:1753[] which supports:
** Mocking of final classes and final methods
** Mocking of static methods
** Mocking of classes and interface from different classloaders spockPull:1878[]
** Requires `org.mockito:mockito-core` >= 4.11 in the test class path
* Add support for mocking of static methods also for Java code with the new API `SpyStatic()` spockPull:1756[]
** The <<interaction_based_testing.adoc#static-mocks,static mock methods>> will delegate the creation to the mock makers
* Add <<spock_primer.adoc#verify-each,verifyEach>> method to perform assertions on each element of an `Iterable` spockPull:1887[], spockPull:2043[]
* Add <<extensions.adoc#parameter-injection,annotation extensions for parameters>> spockPull:1599[]
* Add support for <<extensions.adoc#extension-store,keeping state in extensions>> spockPull:1692[]
* Add <<extensions.adoc#spock-interceptors,feature-scoped interceptors>> spockPull:1844[]
* Add `@Snapshot` extension for <<extensions.adoc#snapshot-testing,snapshot testing>> spockPull:1873[]
* Add `!!` as <<spock_primer.adoc#opt-out-of-condition-handling,opt-out operator for assertions>> spockPull:1532[]

=== Breaking Changes

* _This affects users of the `@Snapshot` extension, only if you were using the snapshotter in parent specification classes._ +
`@Snapshot` used to look up snapshots in directories named after the class containing feature methods. Now, the snapshots will be loaded from directories named after the bottom class in the specification hierarchy. The motivation of the change is to allow users to define features in base specification classes, but overwrite expected snapshots per child specification.
spockPull:2112[]

* _Most users will probably be unaffected by this change as it only becomes relevant in a multithreaded situation where multiple threads do interaction invocations that care about shared state._ +
Calculated responses for interactions (`>> { ... }`) previously were all executed synchronized on the respective mock controller instance, so could safely mutate shared state to a certain degree, even if the invocations were happening
on different threads.
This also caused that one response calculation could not wait on something happening in another response calculation, as they were all executed sequentially due to the synchronization.
Starting with this release, the response calculations are no longer happening synchronized.
If you depend on shared state in such calculations, you now have to make sure yourself, that this is done in a thread-safe manner.
spockPull:1910[]

* _This should not affect most users, only if you were subclassing `SingleResponseGenerator` and doing unusual things._ +
`SingleResponseGenerator#isAtEndOfCycle` is now `final` and `SingleResponseGenerator#doRespond` is now `protected`.
When subclassing `SingleResponseGenerator` it does not make sense to override the first method, and it does not make sense to call the second method from somewhere else.
spockPull:1910[]

* Calling `old(...)` with multiple arguments is now a compilation error. Previously the additional arguments were simply ignored.
* Creating `GroovyMock`/`GroovyStub`/`GroovySpy` for an already mocked type will now fail.
* Creating a global `GroovyMock`/`GroovyStub`/`GroovySpy` when <<parallel_execution.adoc#parallel-execution, parallel execution>> is enabled,
will now require that the spec is annotated with <<parallel_execution.adoc#isolated-execution, @Isolated>> or `@ResourceLock(org.spockframework.runtime.model.parallel.Resources.META_CLASS_REGISTRY)`. See <<interaction_based_testing.adoc#global-mocks-parallel-execution, Global mocks and parallel execution>> spockPull:1848[]
* `@TempDir` `spock.tempDir.keep` has been replaced by `spock.tempdir.cleanup`. See <<extensions.adoc#temp-dir-cleanup,TempDir Cleanup>> spockPull:1525[]

=== Misc

* Fix handling of condition method calls and Groovy `with()` method spockPull:2162[]
** This could break tests using `with()` which relied on the bug in the past spockIssue:2269[]
** Use the Spock `with(yourObject)` instead of `yourObject.with()` or prefix it `!!` to fix your test
* Fix module testing not working due to call to JUnit internal API spockPull:2187[]
** This also fixes the usage of Spock with JUnit 6 in OSGi environments

Thanks to all the contributors to this release: Andreas Turban, Björn Kautler, Choosechee, Christoph Loy, Leonard Brünings, Thanos Tsiamis, Marcin Zajączkowski, Pavlo Shevchenko, Goooler, Jérôme Prinet, jochenberger, Michał Wiśniewski, Nelson Osacky, OhioDschungel6, RahulGautamSingh, Said Boudjelda, soosue, Tasuku Nakagawa

== 2.4-M7 (2025-11-23)

=== Highlights

* Add support for Groovy 5.0 spockIssue:2196[]

=== Misc

* Improve Spock is also tested to run correctly on Java 25 LTS spockPull:2212[]
* Fix handling of `@Verify` and `@VerifyAll` spockIssue:2150[]
* Fix handling of condition method calls spockPull:2162[]
* Fix vararg handling in `SpyStatic` spockIssue:2161[]
* Fix incompatibility with JUnit 6 in OSGi environment spockIssue:2231[]
* Fix OSGi metadata by pinning the `Require-Capability:osgi.ee=JavaSE` to Java `8` spockPull:2233[]
* Fix NPE in `SpecRunHistory.sortFeatures` when duration is missing spockIssue:2234[]
* Fix `Retry` extension does not mesh with `TestAbortedException` and `PendingFeature` spockIssue:1863[]
* Fix display of caught exceptions within `verifyEach` blocks spockPull:2163[]
* Fix extensions that call `invocation.proceed()` multiple times like `@Retry` does spockIssue:1862[]
* Fix setting the whole argument array of an invocation spockPull:2240[]
* Fix `SpyStatic()` with an interaction closure throws NullPointerException spockPull:2254[]

Thanks to all the contributors to this release: Andreas Turban, Björn Kautler, Christoph Loy, Leonard Brünings, Thanos Tsiamis

== 2.4-M6 (2025-04-15)

=== Highlights

* Add support for defining condition blocks with implicit assertions in helper methods annotated with `@Verify` or `@VerifyAll` spockPull:2112[]

=== Breaking Changes

* _This affects users of the `@Snapshot` extension, only if you were using the snapshotter in parent specification classes._ +
`@Snapshot` used to look up snapshots in directories named after the class containing feature methods. Now, the snapshots will be loaded from directories named after the bottom class in the specification hierarchy. The motivation of the change is to allow users to define features in base specification classes, but overwrite expected snapshots per child specification.
spockPull:2112[]

=== Misc

* Improve publish module-alignment metadata spockPull:2082[]
* Improve render multidimensional arrays in comparisons and invocation matchers spockPull:2107[]
* Improve replace unnecessary reflection spockPull:2115[]
* Fix ExtensionException in OSGi environment for global extension spockIssue:2076[]
** This issue was introduced with spockPull:1995[]
* Fix `@RestoreSystemProperties` not restoring state between iterations of a data-driven feature spockIssue:2104[]
* Fix `VerifyError: Stack map does not match the one at exception handler` introduced in 2.4-M5 spockIssue:2080[]
* Fix throw `SpockMultipleFailuresError` instead of a generic `MultipleFailuresError` in case of multiple failed assertions spockPull:2112[]
* Fix cross-multiplication of multi-assignment data providers spockPull:2078[]
* Fix using the same previous data table column multiple times in the same cell spockPull:2084[]
* Fix unintuitive behavior by removing the optimization which data provider is remembered in a multiplication spockPull:2119[]
* Fix several bugs in cross-multiplication implementation spockPull:2123[]
* Fix filter blocks with shared fields and derived data variables spockPull:2088[]
* Fix combined labels with comments being ignored spockPull:2121[]
* Fix boxed Boolean `is` getter methods not properly mocked in Groovy <= 3 spockIssue:2131[]

Thanks to all the contributors to this release: Andreas Turban, Björn Kautler, Christoph Loy, Marcin Zajączkowski, Pavlo Shevchenko

== 2.4-M5 (2025-01-07)

=== Highlights

* Add support for combining two or more data providers using Cartesian product spockIssue:1062[]
* Add support for a `filter` block after a `where` block to filter out unwanted iterations spockPull:1927[]
* Add <<extensions.adoc#block-listener,`IBlockListener`>> extension point to listen to block execution events within feature methods spockPull:1575[]

=== Misc

* Add `globalTimeout` to the  `@Timeout` extension to apply a timeout to all features in a specification, configurable via the Spock configuration file spockPull:1986[]
* Add new <<extensions.adoc#default-value-provider,`IDefaultValueProviderExtension`>> extension point to add support for special classes in the Stub's default `EmptyOrDummyResponse` spockPull:1994[]
* Add support for Groovy-4-style range expressions spockIssue:1956[]
* Add `IStatelessAnnotationDrivenExtension` to allow a single extension instance to be reused across all specifications spockPull:2055[]
* Add new well-known versions to `Jvm` helper to support versions up to `29` spockPull:2057[]
** Built-in extensions have been updated to use this new interface where applicable
* Add best-effort error reporting for interactions on final methods when using the `byte-buddy` mock maker spockIssue:2039[]
* Add support for `@FailsWith` to assert an exception message spockIssue:2039[]
* Add support for accessing the `IStore` via `ISpecificationContext` spockPull:2064[]
* Add support for ContextClassLoader when loading optional classes via `ReflectionUtil` spockPull:1995[]
** This enables the loading of optional classes in, e.g., OSGi environments
* Improve `@Timeout` extension will now use virtual threads if available spockPull:1986[]
* Improve mock argument matching; types constraints or arguments in interactions can now handle primitive types like `_ as int` spockIssue:1974[]
* Improve `verifyEach` to accept an optional second index parameter for the assertion block closure spockPull:2043[]
* Improve size of data providers is no longer calculated multiple times but only once spockPull:2032[]
* Improve documentation about data providers and `size()` calls spockIssue:2022[]
* Improve `EmbeddedSpecRunner` and `EmbeddedSpecCompiler` now support the construction with a custom `ClassLoader` spockPull:1988[]
** This allows the use of these classes in an OSGi environment, where the class imports in the embedded spec are not visible to the Spock OSGi bundle ClassLoader
* Fix a mocking issue with the ByteBuddy MockMaker when using multiple classloaders in Java 21 spockIssue:2017[]
* Fix the mocking of final classes via `@SpringBean` and `@SpringSpy` spockIssue:1960[]
* Fix exception when using `@RepeatUntilFailure` with a data provider with unknown iteration amount spockPull:2031[]
* Fix compile error with single explicit assert in switch expression branch spockIssue:1845[]

Thanks to all the contributors to this release: Andreas Turban, Björn Kautler, Christoph Loy, Marcin Zajączkowski

== 2.4-M4 (2024-03-21)

* Fix nested regex finding in conditions spockPull:1931[]
** Fixes spockIssue:1930[] a regression introduced in M2 by spockPull:1921[]

Thanks to all the contributors to this release: Björn Kautler,

== 2.4-M3 (2024-03-21)

=== Breaking Changes

* _Most users will probably be unaffected by this change as it only becomes relevant in a multithreaded situation where multiple threads do interaction invocations that care about shared state._ +
  Calculated responses for interactions (`>> { ... }`) previously were all executed synchronized on the respective mock controller instance, so could safely mutate shared state to a certain degree, even if the invocations were happening
  on different threads.
  This also caused that one response calculation could not wait on something happening in another response calculation, as they were all executed sequentially due to the synchronization.
  Starting with this release, the response calculations are no longer happening synchronized.
  If you depend on shared state in such calculations, you now have to make sure yourself, that this is done in a thread-safe manner.
  spockPull:1910[]

* _This should not affect most users, only if you were subclassing `SingleResponseGenerator` and doing unusual things._ +
  `SingleResponseGenerator#isAtEndOfCycle` is now `final` and `SingleResponseGenerator#doRespond` is now `protected`.
  When subclassing `SingleResponseGenerator` it does not make sense to override the first method, and it does not make sense to call the second method from somewhere else.
  spockPull:1910[]

=== Misc

* Add option to create Groovy spies with existing instances spockPull:1825[]
* Improve Spock's documentation by automatically linking source snippets in the docs to the code spockPull:1904[]
* Improve `@Retry` extension parallel-safeness spockPull:1701[]
* Improve `@RepeatUntilFailure` by allowing multiple annotations in the same specification spockPull:1912[]
* [.line-through]#Improve collection matchers by supporting them in nested in complex assertions spockPull:1921[]#
* Improve stacktrace filtering by also handling suppressed exceptions spockPull:1923[]
* Fix possible deadlock when blocking in mock response generators spockPull:1910[]
** Fix fallout of spockPull:1885[] introduced in M2
** This actually fixes the issues: spockIssue:583[], spockIssue:1882[], spockIssue:1899[]
* Fix possible `StackOverflowError` when filtering exception cause loops spockPull:1922[]
* Fix NullPointerException after exception in data provider spockPull:1925[]

Thanks to all the contributors to this release: Andreas Turban, Björn Kautler, Marcin Zajączkowski

== 2.4-M2 (2024-02-26)

=== Highlights

* Add support for pluggable <<extensions.adoc#mock-makers,mock makers>> loaded via ServiceLoader spockPull:1746[]
** This allows external libraries to contribute mocking logic to Spock and use the same API for the users
** You can select the used mock maker during mock creation: `Mock(mockMaker:MockMakers.byteBuddy)`
* Add <<extensions.adoc#mock-makers-mockito,mockito>> mock maker spockPull:1753[] which supports:
** Mocking of final classes and final methods
** Mocking of static methods
** Mocking of classes and interface from different classloaders spockPull:1878[]
** Requires `org.mockito:mockito-core` >= 4.11 in the test class path
* Add support for mocking of static methods also for Java code with the new API `SpyStatic()` spockPull:1756[]
** The <<interaction_based_testing.adoc#static-mocks,static mock methods>> will delegate the creation to the mock makers
* Add <<spock_primer.adoc#verify-each,verifyEach>> method to perform assertions on each element of an `Iterable` spockPull:1887[]
* Add <<extensions.adoc#parameter-injection,annotation extensions for parameters>> spockPull:1599[]
* Add support for <<extensions.adoc#extension-store,keeping state in extensions>> spockPull:1692[]
* Add <<extensions.adoc#spock-interceptors,feature-scoped interceptors>> spockPull:1844[]
* Add `@Snapshot` extension for <<extensions.adoc#snapshot-testing,snapshot testing>> spockPull:1873[]
* Add `!!` as <<spock_primer.adoc#opt-out-of-condition-handling,opt-out operator for assertions>> spockPull:1532[]

=== Breaking Changes

* Calling `old(...)` with multiple arguments is now a compilation error. Previously the additional arguments were simply ignored.
* Creating `GroovyMock`/`GroovyStub`/`GroovySpy` for an already mocked type will now fail.
* Creating a global `GroovyMock`/`GroovyStub`/`GroovySpy` when <<parallel_execution.adoc#parallel-execution, parallel execution>> is enabled,
  will now require that the spec is annotated with <<parallel_execution.adoc#isolated-execution, @Isolated>> or `@ResourceLock(org.spockframework.runtime.model.parallel.Resources.META_CLASS_REGISTRY)`. See <<interaction_based_testing.adoc#global-mocks-parallel-execution, Global mocks and parallel execution>> spockPull:1848[]
* `@TempDir` `spock.tempDir.keep` has been replaced by `spock.tempdir.cleanup`. See <<extensions.adoc#temp-dir-cleanup,TempDir Cleanup>> spockPull:1525[]

=== Misc
* Add support for parameter injection of `@TempDir`
* Add cleanup switch for `@TempDir` spockPull:1525[]
* Add support for creation of global Groovy mocks for abstract classes spockPull:1754[]
* Add optional reason to `@ResourceLock` spockPull:1890[]
* Add optional reason to `@Execution` spockPull:1576[]
* Add `onTimeout` support for `PollingConditions` spockPull:1853[]
* Add `SpecInfo#getAll...Methods()` methods spockPull:1770[]
* Add array support to collection conditions spockPull:1734[]
* Add support for logging thread dumps when <<extensions.adoc#timeout-extension,@Timeout interrupts>> are ignored spockPull:1658[]
* Add implied features to force execution of features even when removed by a build tool spockPull:1598[]
* Improve StackTraceFilter by ignoring `java.lang.invoke.*` spockPull:1892[]
* Improve `@TempDir` field injection, now it happens before field initialization, so it can be used by other field initializers.
* Improve Spock-Compiler does not use wrapper types anymore spockPull:1765[]
* Improve reduce lock contention of the `byte-buddy` mock maker, when multiple mocks are created concurrently spockPull:1778[]
* Improve `@Use` on feature and fixture method for parallel execution spockPull:1691[]
* Improve IDE support
** by adding a closure signature hint that derives closure argument type from variable type spockPull:1785[]
** by adding missing closure hints for Spy(T, Closure) spockPull:1786[]
** by adding GDSL/DSLD for ConditionalExtension's annotations spockPull:1808[]
** by making `spock.gdsl` fail-safe and cover some more cases spockPull:1783[]
* Improve RunContexts behavior in multithreaded executions spockPull:1758[], spockPull:1846[]
* Improve generic handling by replacing `gentyref` code with https://github.com/leangen/geantyref[geantyref] library spockPull:1743[]
** This is now a required dependency used by spock: `io.leangen.geantyref:geantyref:1.3.14`
* Improve handling of passing `null` to `thrown()` to be consistent with mock object creation spockPull:1799[]
* Improve `old(...)` calls by validating their argument count spockPull:1810[]
* Improve robustness of the AST transformation against missing classes in the compile classpath spockPull:1704[]
* Improve handling of `shared.` conditions in `@IgnoreIf`/`@Requires`, the condition is now checked before creating data providers spockPull:1711[]
* Fix issue with mocks of Groovy classes, where the Groovy MOP for `@Internal` methods was not honored by the `byte-buddy` mock maker spockPull:1729[]
** This fixes multiple issues with Groovy MOP: spockIssue:1501[], spockIssue:1452[], spockIssue:1608[] and spockIssue:1145[]
* Improve support for generic return types for mocks spockPull:1731[]
** This fixes the issues: spockIssue:520[], spockIssue:1163[]
* Fix the lifecycle of simple features spockPull:1675[]
* Fix exception when configured `baseDir` was not existing, now `@TempDir` will create the baseDir directory if it is missing.
* Fix bad error message for collection conditions, when one of the operands is `null`
* Fix docs about initializer method interceptors spockPull:1666[]
* [.line-through]#Fix possible deadlock, when blocking in mock response generators spockPull:1885[]#
** [.line-through]#This fixes the issues: spockIssue:583[], spockIssue:1882[]#
* Fix SpringSpy not working with `DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD` spockPull:1869[]
* Fix null handling for collection conditions spockPull:1858[]
* Fix interceptor contexts spockPull:1676[]
* Fix properly call `IRunListener.specSkipped` and `.featureSkipped` spockPull:1811[]
* Fix defining responses for additionalInterfaces spockPull:1730[]
* Fix lost execution mode for iteration nodes of implied data-driven features spockPull:1615[]
* Fix docs how to register all possible interceptors spockPull:1667[], spockPull:1824[]
* Document `@ConditionBlock` Annotation spockPull:1709[]
* Document `old`-Method spockPull:1708[]
* Document for DetachedMockFactory spockPull:1728[]
* Clarify documentation for global Mocks spockPull:1755[]

Thanks to all the contributors to this release:  Andreas Turban, Björn Kautler, Goooler, Jérôme Prinet, Marcin Zajączkowski, Michał Wiśniewski, Nelson Osacky, Pavlo Shevchenko, RahulGautamSingh, Said Boudjelda, Tasuku Nakagawa, jochenberger, soosue

== 2.4-M1 (2022-11-30)

* Fix issues with Spring 6/Spring Boot 3 spockPull:1541[]
