[[utilities]]
= Utilities
include::include.adoc[]

[[mutable-clock]]
== Testing Time with `MutableClock`

When working with dates or time we often have the problem of writing stable tests.
Java only provides a `FixedClock` for testing.
However, often time related code has to deal with the change of time,
so a fixed clock is not enough or makes the test harder to follow.

The prerequisite for using both `FixedClock` and Spocks `MutableClock` is that the production code,
actually uses a configurable `Clock` and not just the parameterless `Instant.now()`
or the corresponding methods in the other `java.time.*` classes.

=== Example

.Class under Test
[source,groovy,indent=0]
----
include::{sourcedir}/utilities/AgeFilter.java[tag=age-filter-class]
----
<1> `Clock` is injected via constructor
<2> `Clock` is used to get the current date

.Test
[source,groovy,indent=0]
----
include::{sourcedir}/utilities/MutableClockDocSpec.groovy[tag=age-filter-spec]
----
<1> `MutableClock` created with a well known time
<2> `Clock` is injected via constructor
<3> `age` is less than `18` so the result is `false`
<4> the clock is advanced by one day
<5> `age` is equal to `18` so the result is `true`

There are many more ways to modify `MutableClock` just have a look at the JavaDocs, or the test code `spock.util.time.MutableClockSpec`.

[[collection-conditions]]
== Collection Conditions

Sometimes, you want to assert the elements of a collection regardless of their order.
The Groovy way to do this is to cast both to `Set`, i.e. `x as Set == [1, 2, 3] as Set`.
While this works, it is very noisy.

Since Spock 2.1 you can use two new conditions:

* `x =~ [1, 2, 3]` is a lenient match, i.e., checking that x contains at least one instance of every item in the list (same semantics as casting both to `Set` before comparing).
* `x ==~ [1, 2, 3, 3]` is a strict match, i.e., checking that x contains exactly the items in the list regardless of their order (using Hamcrest's `containsInAnyOrder` under the hood).

=== Lenient Match
[source,groovy,indent=0]
----
include::{sourcedir}/utilities/CollectionConditions.groovy[tag=lenient-matcher]
----

[source,indent=0]
----
include::{sourcedir}/utilities/CollectionConditions.groovy[tag=lenient-matcher-result]
----

=== Strict Match
[source,groovy,indent=0]
----
include::{sourcedir}/utilities/CollectionConditions.groovy[tag=strict-matcher]
----
[source,indent=0]
----
include::{sourcedir}/utilities/CollectionConditions.groovy[tag=strict-matcher-result]
----

NOTE: Both operands must be `Iterable` for this to work.
Otherwise, it will be treated like the standard groovy https://groovy-lang.org/operators.html#_find_operator[find operator] or https://groovy-lang.org/operators.html#_match_operator[match operators].

[[fs-fixture]]
== Interact with the file system using `FsFixture`

In integration tests you often have to prepare the file system for a test.
For trivial cases like creating a single temp directory, you can use the <<extensions.adoc#_temp_dir,@TempDir>> extension directly.
However, for more complex cases like creating a directory tree `FsFixture` offers convenience and better readability.

=== Examples

.Creating a directory tree
[source,groovy,indent=0]
----
include::{sourcedir}/utilities/FsFixtureSpec.groovy[tag=fs-fixture-usage]
----

TIP: To get the nice Groovy methods for `Path`, you need to add a dependency on `groovy-nio`.
