name: 'Verify Docs'

on:
  push:
    branches-ignore:
      - master
      - gh-pages
  pull_request:
  merge_group:

# https://stackoverflow.com/a/72408109/16358266
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  docs-and-javadoc:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
        with:
          # Codecov needs fetch-depth > 1
          fetch-depth: 2
      - name: 'Set up JDKs'
        uses: ./.github/actions/setup-build-env
        with:
          additional-java-version: 21
      - name: 'Install GraphViz'
        run: sudo apt update && sudo apt install --yes graphviz
      - name: 'Build Docs'
        run: ./gradlew --no-parallel --stacktrace asciidoctor javadoc "-Dvariant=4.0" "-DjavaVersion=21"
      - name: 'Archive and upload docs'
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            build/docs/**
            build/javadoc/**
